### ISSUE TITLE
InvalidParameterError

### ISSUE THREAD

**Issue by wsnoble** [freejstone/Percolator-RESET#1]
I tried to run using a Tide output file from Crux version Crux version 4.1-81a6e03-2023-09-01, but I got an error.  See full output log below.

```
python3 ~/proj/freestone/Percolator-RESET/functions/do_FDR_percolator.py --seed 1 --FDR_threshold 0.3 --overwrite T --narrow F --output_dir . --file_root foo 03022016_Clara_MP_Fraction_02/tide-search.pin Solanum-lycopersicum/tide-index/tide-index.peptides.txt
checkCPU: macOS-13.6-arm64-arm-64bit 
2023-10-31 10:08:27.712312 
Command used: /Users/wnoble/proj/freestone/Percolator-RESET/functions/do_FDR_percolator.py --seed 1 --FDR_threshold 0.3 --overwrite T --narrow F --output_dir . --file_root foo 03022016_Clara_MP_Fraction_02/tide-search.pin Solanum-lycopersicum/tide-index/tide-index.peptides.txt
Successfully read in arguments. 
Using seed: 1. 
Reading in search file(s) and peptide list(s). 
Taking top 1 PSMs. 
Doing peptide-stem level competition. 
Dropping the features: enzInt. 
Conducting iterative SVM.
iteration: 0.
Traceback (most recent call last):
  File "/Users/wnoble/proj/freestone/Percolator-RESET/functions/do_FDR_percolator.py", line 368, in <module>
    main()
  File "/Users/wnoble/proj/freestone/Percolator-RESET/functions/do_FDR_percolator.py", line 230, in main
    train_power, std_power, true_power, df_new, train_all_new, model, columns_trained = pf.do_svm(df_all_scale.copy(), train_all.copy(), df_all.copy(), folds=folds, Cs=[
  File "/Users/wnoble/proj/freestone/Percolator-RESET/functions/percolator_functions.py", line 547, in do_svm
    grid = train_cv(SVM_train_labels_iter, SVM_train_features_iter,
  File "/Users/wnoble/proj/freestone/Percolator-RESET/functions/percolator_functions.py", line 345, in train_cv
    grid.fit(df, labels)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/denovofdr/lib/python3.10/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/denovofdr/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 898, in fit
    self._run_search(evaluate_candidates)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/denovofdr/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 1422, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/denovofdr/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 875, in evaluate_candidates
    _warn_or_raise_about_fit_failures(out, self.error_score)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/denovofdr/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 414, in _warn_or_raise_about_fit_failures
    raise ValueError(all_fits_failed_message)
ValueError: 
All the 18 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
18 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/denovofdr/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/denovofdr/lib/python3.10/site-packages/sklearn/base.py", line 1145, in wrapper
    estimator._validate_params()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/denovofdr/lib/python3.10/site-packages/sklearn/base.py", line 638, in _validate_params
    validate_parameter_constraints(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/denovofdr/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 96, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_iter' parameter of LinearSVC must be an int in the range [0, inf). Got 10000000.0 instead.
```

[tide-search.pin.txt](https://github.com/freejstone/Percolator-RESET/files/13217377/tide-search.pin.txt)

The peptide list file is [here](https://noble.gs.washington.edu/~wnoble/temp/tide-index.peptides.txt.gz).

**Comment by wsnoble** [comment]
I fixed this by casting max_iter to int (`max_iter=int(1e7)`) in three places in percolator_functions.py.

**Comment by freejstone** [comment]
Thanks Bill! Your fix has been added.
