### ISSUE TITLE
Cannot set a DataFrame

### ISSUE THREAD

**Issue by azelter** [freejstone/Percolator-RESET#9]
This command runs fine on one PIN file (comet.pin.txt [too big to attach]), but not a second one (az.comet.mod.pin.txt [also too big to attach]), which is a subset of the first containing only lines pertaining to PSMs with a 471.1504 modification.
`python -m percolator_RESET --seed 1 --get_psms T --reverse T --report_decoys T --output_dir output --file_root az.comet.mod --initial_dir Xcorr --overwrite T az.comet.mod.pin.txt`

The error output by running this command on az.comet.mod.pin is below. Everything seems to run fine until the end when the following error is output:
`Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/reset/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/alex/anaconda3/envs/reset/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/alex/anaconda3/envs/reset/lib/python3.10/site-packages/percolator_RESET/__main__.py", line 405, in <module>
    main()
  File "/home/alex/anaconda3/envs/reset/lib/python3.10/site-packages/percolator_RESET/__main__.py", line 387, in main
    uf.report_psms(df_new, PSMs, get_psms, dynamic_competition, scale, model, isolation_window, columns_trained, initial_dir, output_dir, file_root)
  File "/home/alex/anaconda3/envs/reset/lib/python3.10/site-packages/percolator_RESET/utility_functions.py", line 426, in report_psms
    df_extra = create_cluster(PSMs.copy(
  File "/home/alex/anaconda3/envs/reset/lib/python3.10/site-packages/percolator_RESET/utility_functions.py", line 215, in create_cluster
    targets["mass_plus"] = targets.groupby('original_target_sequence', group_keys=False).apply(
  File "/home/alex/anaconda3/envs/reset/lib/python3.10/site-packages/pandas/core/frame.py", line 4301, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/alex/anaconda3/envs/reset/lib/python3.10/site-packages/pandas/core/frame.py", line 4459, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column mass_plus`

**Comment by freejstone** [comment]
Hi Alex!

Are you able to share with me a small subset of az.comet.mod.pin.txt that is uploadable?

Thanks!

**Comment by freejstone** [comment]
Copying my comment from slack:

Ok i see the problem. its because az.comet.mod.pin.txt returns zero peptide discoveries, so when it tries to determine the PSMs associated to the zero discovered peptides, it bugs out. This should be obviously handled with a message of sorts, so ill make note of this in the github issue and get to a fix soon. It will be hard to discover peptides at the 1% FDR level in this file. Of the target and PSMs with XCorr score above 2, there is only 98 target and 72 decoy PSMs.

**Comment by freejstone** [comment]
This has been kind of fixed for now...I just added an if statement to check if the dataframe is empty and it skips reporting the additional output files. Hope that suffices for now!
